baseURL = 'https://lance-terminal.github.io/asgar/'
languageCode = 'en-us'
title = 'Asgar'
theme = "poison"

[pagination]
    pagerSize = 10

pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[params]
    brand = "Asgar"     # name of site - appears in the sidebar
    remote_brand_image = 'https://avatars.githubusercontent.com/u/101709186?v=4' # path to a remote file
    description = "Digital Forensics & Incident Response" # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    favicon = "/icons/favicon.png"
